### ISSUE TITLE
File import SADD Problem

### ISSUE THREAD

**Issue by GreatAg** [redis/riot#141]
Hello
I have a json file (which i exported from my redis set using riot) like this:
```
[
  {
    "key": "malware_hashes",
    "type": "set",
    "value": ["1", "2", "3", "4", "5"],
    "ttl": -1,
    "mem": 0
  }
]
```

when i import this into redis, this create my key correctly but it count all the elements in members array as on member and add value array to my set

here is my command for import:

`riot -h <host> -a <pass> file-import ./myfile.json sadd --keys key --members value`

and here is the redis data after import:

```127.0.0.1:6379> keys *
1) "malware_hashes"
127.0.0.1:6379> SMEMBERS malware_hashes
1) "[1, 2, 3, 4, 5]"
```

i want my redis output become like this:

```
127.0.0.1:6379> keys *
1) "malware_hashes"
127.0.0.1:6379> SMEMBERS malware_hashes
1) "1"
2) "2"
3) "3"
4) "4"
5) "5"
```
can someone help me resolve this issue?
Thanks.

**Comment by jruaux** [comment]
You want to use the `dump-import` command instead of `file-import`

**Comment by GreatAg** [comment]
Thanks a lot
