### ISSUE TITLE
replicate source does not support --client

### ISSUE THREAD

**Issue by timothystewart6** [redis/riot#159]
Hi.  It seems that `ping` supports `--client` to set the client name (or unset my case).  I need to unset the client with this arg because I don't have access to set this config in GCP on Redis Memorystore so the workaround is:

```bash
riot ping -u redis://10.213.18.228:6379 --client=""
```

This works great for `ping` however it looks like this argument is missing from `replicate`.

`replicate` supports `--target-client` but not `--source-client` or `--client`

This causes the command to throw an exception (just like using `ping` without `--client=""` in my case.

```bash
riot replicate --mode live --target-cluster redis://10.213.18.228:6379 redis://10.128.0.172:6379 --debug
```

```log
...
Caused by: io.lettuce.core.RedisCommandExecutionException: ERR unknown command 'CLIENT', with args beginning with: 'SETNAME' 'RIOT4.1.4-SNAPSHOT'
	at io.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:147)
	at io.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:116)
```
if I could use `--client` or better yet `--source-client` argument to unset this for the source I can then run `replicate`

Ideally I would like to do this:

```bash
riot replicate --mode live --target-cluster --target-client="" --source-client="" redis://10.213.18.228:6379 redis://10.128.0.172:6379 --debug

```
I am using the `v4.1.3` and even tried the `early-access` release.  Neither support it.

Thank you!

**Comment by jruaux** [comment]
Thanks I just added a `--source-client` option

**Comment by timothystewart6** [comment]
Wow, thank you!
